apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-spring-boot-web
  name: my-spring-boot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-boot-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-spring-boot-web
    spec:
      containers:
      - image: yongking50/spring-boot-web:v1
        name: spring-boot-web
        resources: {}
status: {}